package com.changuang.domain.entity;
// Generated 2017-12-1 14:27:22 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * AdminUser generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "admin_user", catalog = "tochatting")
public class AdminUser implements java.io.Serializable {

	private Integer recid;
	private Integer utypeRecid;
	private String adminLoginname;
	private String adminShowname;
	private String adminPasswrod;
	private String adminPhone;
	private Integer adminStatus;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date createTime;
	private String adminTencent;
	private String adminUsername;
	private String adminId;

	public AdminUser() {
	}

	public AdminUser(Integer utypeRecid, String adminLoginname, String adminShowname, String adminPasswrod,
			String adminPhone, Integer adminStatus, Date createTime, String adminTencent, String adminUsername,
			String adminId) {
		this.utypeRecid = utypeRecid;
		this.adminLoginname = adminLoginname;
		this.adminShowname = adminShowname;
		this.adminPasswrod = adminPasswrod;
		this.adminPhone = adminPhone;
		this.adminStatus = adminStatus;
		this.createTime = createTime;
		this.adminTencent = adminTencent;
		this.adminUsername = adminUsername;
		this.adminId = adminId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "utype_recid")
	public Integer getUtypeRecid() {
		return this.utypeRecid;
	}

	public void setUtypeRecid(Integer utypeRecid) {
		this.utypeRecid = utypeRecid;
	}

	@Column(name = "admin_loginname", length = 100)
	public String getAdminLoginname() {
		return this.adminLoginname;
	}

	public void setAdminLoginname(String adminLoginname) {
		this.adminLoginname = adminLoginname;
	}

	@Column(name = "admin_showname", length = 20)
	public String getAdminShowname() {
		return this.adminShowname;
	}

	public void setAdminShowname(String adminShowname) {
		this.adminShowname = adminShowname;
	}

	@Column(name = "admin_passwrod", length = 20)
	public String getAdminPasswrod() {
		return this.adminPasswrod;
	}

	public void setAdminPasswrod(String adminPasswrod) {
		this.adminPasswrod = adminPasswrod;
	}

	@Column(name = "admin_phone", length = 20)
	public String getAdminPhone() {
		return this.adminPhone;
	}

	public void setAdminPhone(String adminPhone) {
		this.adminPhone = adminPhone;
	}

	@Column(name = "admin_status")
	public Integer getAdminStatus() {
		return this.adminStatus;
	}

	public void setAdminStatus(Integer adminStatus) {
		this.adminStatus = adminStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "admin_tencent", length = 20)
	public String getAdminTencent() {
		return this.adminTencent;
	}

	public void setAdminTencent(String adminTencent) {
		this.adminTencent = adminTencent;
	}

	@Column(name = "admin_username", length = 20)
	public String getAdminUsername() {
		return this.adminUsername;
	}

	public void setAdminUsername(String adminUsername) {
		this.adminUsername = adminUsername;
	}

	@Column(name = "admin_id", length = 20)
	public String getAdminId() {
		return this.adminId;
	}

	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

}
