package com.changuang.domain.entity;
// Generated 2017-12-25 17:57:09 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * AnchorSheet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "anchor_sheet", catalog = "tochatting")
public class AnchorSheet implements java.io.Serializable {

	private Integer recid;
	private Integer userRecid;
	private Float accumulativeGift;
	private Float beconsumedAmount;
	private Float amountOfcash;
	private Float balance;
	private Float anchorGrade;
	private Float accumulativeTime;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date createTime;
	private String userName;
	private String userIdcord;
	private String userAddress;
	private Float voiceChat;
	private Float videoChat;
	private Float anchorGlamour;
	private String anchorClass;
	@DateTimeFormat( pattern = "yyyy-MM-dd" )
	private Date userBirthday;
	private String userOccupation;
	private String myPhoto;
	private String chatAbility;
	private Integer isHot;
	private Integer isRecommend;
	private Integer isForefront;
	private String smallPhoto;

	public AnchorSheet() {
	}

	public AnchorSheet(Integer userRecid, Float accumulativeGift, Float beconsumedAmount, Float amountOfcash,
			Float balance, Float anchorGrade, Float accumulativeTime, Date createTime, String userName,
			String userIdcord, String userAddress, Float voiceChat, Float videoChat, Float anchorGlamour,
			String anchorClass, Date userBirthday, String userOccupation, String myPhoto, String chatAbility,
			Integer isHot, Integer isRecommend, Integer isForefront, String smallPhoto) {
		this.userRecid = userRecid;
		this.accumulativeGift = accumulativeGift;
		this.beconsumedAmount = beconsumedAmount;
		this.amountOfcash = amountOfcash;
		this.balance = balance;
		this.anchorGrade = anchorGrade;
		this.accumulativeTime = accumulativeTime;
		this.createTime = createTime;
		this.userName = userName;
		this.userIdcord = userIdcord;
		this.userAddress = userAddress;
		this.voiceChat = voiceChat;
		this.videoChat = videoChat;
		this.anchorGlamour = anchorGlamour;
		this.anchorClass = anchorClass;
		this.userBirthday = userBirthday;
		this.userOccupation = userOccupation;
		this.myPhoto = myPhoto;
		this.chatAbility = chatAbility;
		this.isHot = isHot;
		this.isRecommend = isRecommend;
		this.isForefront = isForefront;
		this.smallPhoto = smallPhoto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "user_recid")
	public Integer getUserRecid() {
		return this.userRecid;
	}

	public void setUserRecid(Integer userRecid) {
		this.userRecid = userRecid;
	}

	@Column(name = "accumulative_gift", precision = 12, scale = 0)
	public Float getAccumulativeGift() {
		return this.accumulativeGift;
	}

	public void setAccumulativeGift(Float accumulativeGift) {
		this.accumulativeGift = accumulativeGift;
	}

	@Column(name = "beconsumed_amount", precision = 12, scale = 0)
	public Float getBeconsumedAmount() {
		return this.beconsumedAmount;
	}

	public void setBeconsumedAmount(Float beconsumedAmount) {
		this.beconsumedAmount = beconsumedAmount;
	}

	@Column(name = "amount_ofcash", precision = 12, scale = 0)
	public Float getAmountOfcash() {
		return this.amountOfcash;
	}

	public void setAmountOfcash(Float amountOfcash) {
		this.amountOfcash = amountOfcash;
	}

	@Column(name = "balance", precision = 12, scale = 0)
	public Float getBalance() {
		return this.balance;
	}

	public void setBalance(Float balance) {
		this.balance = balance;
	}

	@Column(name = "anchor_grade", precision = 12, scale = 0)
	public Float getAnchorGrade() {
		return this.anchorGrade;
	}

	public void setAnchorGrade(Float anchorGrade) {
		this.anchorGrade = anchorGrade;
	}

	@Column(name = "accumulative_time", precision = 12, scale = 0)
	public Float getAccumulativeTime() {
		return this.accumulativeTime;
	}

	public void setAccumulativeTime(Float accumulativeTime) {
		this.accumulativeTime = accumulativeTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "user_name", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_idcord", length = 25)
	public String getUserIdcord() {
		return this.userIdcord;
	}

	public void setUserIdcord(String userIdcord) {
		this.userIdcord = userIdcord;
	}

	@Column(name = "user_address", length = 100)
	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	@Column(name = "voice_chat", precision = 12, scale = 0)
	public Float getVoiceChat() {
		return this.voiceChat;
	}

	public void setVoiceChat(Float voiceChat) {
		this.voiceChat = voiceChat;
	}

	@Column(name = "video_chat", precision = 12, scale = 0)
	public Float getVideoChat() {
		return this.videoChat;
	}

	public void setVideoChat(Float videoChat) {
		this.videoChat = videoChat;
	}

	@Column(name = "anchor_glamour", precision = 12, scale = 0)
	public Float getAnchorGlamour() {
		return this.anchorGlamour;
	}

	public void setAnchorGlamour(Float anchorGlamour) {
		this.anchorGlamour = anchorGlamour;
	}

	@Column(name = "anchor_class", length = 20)
	public String getAnchorClass() {
		return this.anchorClass;
	}

	public void setAnchorClass(String anchorClass) {
		this.anchorClass = anchorClass;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "user_birthday", length = 10)
	public Date getUserBirthday() {
		return this.userBirthday;
	}

	public void setUserBirthday(Date userBirthday) {
		this.userBirthday = userBirthday;
	}

	@Column(name = "user_occupation", length = 20)
	public String getUserOccupation() {
		return this.userOccupation;
	}

	public void setUserOccupation(String userOccupation) {
		this.userOccupation = userOccupation;
	}

	@Column(name = "my_photo", length = 200)
	public String getMyPhoto() {
		return this.myPhoto;
	}

	public void setMyPhoto(String myPhoto) {
		this.myPhoto = myPhoto;
	}

	@Column(name = "chat_ability", length = 100)
	public String getChatAbility() {
		return this.chatAbility;
	}

	public void setChatAbility(String chatAbility) {
		this.chatAbility = chatAbility;
	}

	@Column(name = "is_hot")
	public Integer getIsHot() {
		return this.isHot;
	}

	public void setIsHot(Integer isHot) {
		this.isHot = isHot;
	}

	@Column(name = "is_recommend")
	public Integer getIsRecommend() {
		return this.isRecommend;
	}

	public void setIsRecommend(Integer isRecommend) {
		this.isRecommend = isRecommend;
	}

	@Column(name = "is_forefront")
	public Integer getIsForefront() {
		return this.isForefront;
	}

	public void setIsForefront(Integer isForefront) {
		this.isForefront = isForefront;
	}

	@Column(name = "small_photo", length = 200)
	public String getSmallPhoto() {
		return this.smallPhoto;
	}

	public void setSmallPhoto(String smallPhoto) {
		this.smallPhoto = smallPhoto;
	}

}
