package com.changuang.domain.entity;
// Generated 2017-12-1 14:27:22 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * AnchorStatus generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "anchor_status", catalog = "tochatting")
public class AnchorStatus implements java.io.Serializable {

	private Integer recid;
	private String anchorStatusname;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date createTime;

	public AnchorStatus() {
	}

	public AnchorStatus(String anchorStatusname, Date createTime) {
		this.anchorStatusname = anchorStatusname;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "anchor_statusname", length = 20)
	public String getAnchorStatusname() {
		return this.anchorStatusname;
	}

	public void setAnchorStatusname(String anchorStatusname) {
		this.anchorStatusname = anchorStatusname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
