package com.changuang.domain.entity;
// Generated 2017-12-1 14:27:22 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * FriendSheet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "friend_sheet", catalog = "tochatting")
public class FriendSheet implements java.io.Serializable {

	private Integer recid;
	private Integer userRecidone;
	private Integer userRecidtwo;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date createTime;
	private Integer friendStatus;

	public FriendSheet() {
	}

	public FriendSheet(Integer userRecidone, Integer userRecidtwo, Date createTime, Integer friendStatus) {
		this.userRecidone = userRecidone;
		this.userRecidtwo = userRecidtwo;
		this.createTime = createTime;
		this.friendStatus = friendStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "user_recidone")
	public Integer getUserRecidone() {
		return this.userRecidone;
	}

	public void setUserRecidone(Integer userRecidone) {
		this.userRecidone = userRecidone;
	}

	@Column(name = "user_recidtwo")
	public Integer getUserRecidtwo() {
		return this.userRecidtwo;
	}

	public void setUserRecidtwo(Integer userRecidtwo) {
		this.userRecidtwo = userRecidtwo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "friend_status")
	public Integer getFriendStatus() {
		return this.friendStatus;
	}

	public void setFriendStatus(Integer friendStatus) {
		this.friendStatus = friendStatus;
	}

}
