package com.changuang.domain.entity;
// Generated 2018-2-2 9:33:17 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * GiftSheet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "gift_sheet", catalog = "tochatting")
public class GiftSheet implements java.io.Serializable {

	private Integer recid;
	private String giftName;
	private Float giftMoney;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date createTime;
	private String giftPath;
	private Integer isShow;
	private Integer continuous;

	public GiftSheet() {
	}

	public GiftSheet(String giftName, Float giftMoney, Date createTime, String giftPath, Integer isShow,
			Integer continuous) {
		this.giftName = giftName;
		this.giftMoney = giftMoney;
		this.createTime = createTime;
		this.giftPath = giftPath;
		this.isShow = isShow;
		this.continuous = continuous;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "gift_name", length = 20)
	public String getGiftName() {
		return this.giftName;
	}

	public void setGiftName(String giftName) {
		this.giftName = giftName;
	}

	@Column(name = "gift_money", precision = 12, scale = 0)
	public Float getGiftMoney() {
		return this.giftMoney;
	}

	public void setGiftMoney(Float giftMoney) {
		this.giftMoney = giftMoney;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "gift_path", length = 200)
	public String getGiftPath() {
		return this.giftPath;
	}

	public void setGiftPath(String giftPath) {
		this.giftPath = giftPath;
	}

	@Column(name = "is_show")
	public Integer getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Integer isShow) {
		this.isShow = isShow;
	}

	@Column(name = "continuous")
	public Integer getContinuous() {
		return this.continuous;
	}

	public void setContinuous(Integer continuous) {
		this.continuous = continuous;
	}

}
