package com.changuang.domain.entity;
// Generated 2017-12-1 14:27:22 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * HomeUser generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "home_user", catalog = "tochatting")
public class HomeUser implements java.io.Serializable {

	private Integer recid;
	private Integer homeClass;
	private Integer homeRecid;
	private Integer userRecid;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date createTime;

	public HomeUser() {
	}

	public HomeUser(Integer homeClass, Integer homeRecid, Integer userRecid, Date createTime) {
		this.homeClass = homeClass;
		this.homeRecid = homeRecid;
		this.userRecid = userRecid;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "home_class")
	public Integer getHomeClass() {
		return this.homeClass;
	}

	public void setHomeClass(Integer homeClass) {
		this.homeClass = homeClass;
	}

	@Column(name = "home_recid")
	public Integer getHomeRecid() {
		return this.homeRecid;
	}

	public void setHomeRecid(Integer homeRecid) {
		this.homeRecid = homeRecid;
	}

	@Column(name = "user_recid")
	public Integer getUserRecid() {
		return this.userRecid;
	}

	public void setUserRecid(Integer userRecid) {
		this.userRecid = userRecid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
