package com.changuang.domain.entity;
// Generated 2017-12-1 14:27:22 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * HomenewsSheet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "homenews_sheet", catalog = "tochatting")
public class HomenewsSheet implements java.io.Serializable {

	private Integer recid;
	private Integer sendUserrecid;
	private Integer receiveUserrecid;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date createTime;
	private String newsContent;
	private Integer homeRecid;

	public HomenewsSheet() {
	}

	public HomenewsSheet(Integer sendUserrecid, Integer receiveUserrecid, Date createTime, String newsContent,
			Integer homeRecid) {
		this.sendUserrecid = sendUserrecid;
		this.receiveUserrecid = receiveUserrecid;
		this.createTime = createTime;
		this.newsContent = newsContent;
		this.homeRecid = homeRecid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "send_userrecid")
	public Integer getSendUserrecid() {
		return this.sendUserrecid;
	}

	public void setSendUserrecid(Integer sendUserrecid) {
		this.sendUserrecid = sendUserrecid;
	}

	@Column(name = "receive_userrecid")
	public Integer getReceiveUserrecid() {
		return this.receiveUserrecid;
	}

	public void setReceiveUserrecid(Integer receiveUserrecid) {
		this.receiveUserrecid = receiveUserrecid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "news_content")
	public String getNewsContent() {
		return this.newsContent;
	}

	public void setNewsContent(String newsContent) {
		this.newsContent = newsContent;
	}

	@Column(name = "home_recid")
	public Integer getHomeRecid() {
		return this.homeRecid;
	}

	public void setHomeRecid(Integer homeRecid) {
		this.homeRecid = homeRecid;
	}

}
