package com.changuang.domain.entity;
// Generated 2017-12-1 14:27:22 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * LoginSheet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "login_sheet", catalog = "tochatting")
public class LoginSheet implements java.io.Serializable {

	private Integer recid;
	private Integer userRecid;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date createTime;
	private String loginRecid;
	private String loginAddress;

	public LoginSheet() {
	}

	public LoginSheet(Integer userRecid, Date createTime, String loginRecid, String loginAddress) {
		this.userRecid = userRecid;
		this.createTime = createTime;
		this.loginRecid = loginRecid;
		this.loginAddress = loginAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "user_recid")
	public Integer getUserRecid() {
		return this.userRecid;
	}

	public void setUserRecid(Integer userRecid) {
		this.userRecid = userRecid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "login_recid", length = 50)
	public String getLoginRecid() {
		return this.loginRecid;
	}

	public void setLoginRecid(String loginRecid) {
		this.loginRecid = loginRecid;
	}

	@Column(name = "login_address", length = 100)
	public String getLoginAddress() {
		return this.loginAddress;
	}

	public void setLoginAddress(String loginAddress) {
		this.loginAddress = loginAddress;
	}

}
