package com.changuang.domain.entity;
// Generated 2017-10-11 10:28:26 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PageConfig generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "page_config", catalog = "tochatting")
public class PageConfig implements java.io.Serializable {

	private Integer id;
	private String title;
	private String icon;
	private String href;
	private Integer spread;
	private String children;
	private Integer level;
	private Integer status;
	private String parent;

	public PageConfig() {
	}

	public PageConfig(String title) {
		this.title = title;
	}

	public PageConfig(String title, String icon, String href, Integer spread, String children, Integer level,
			Integer status, String parent) {
		this.title = title;
		this.icon = icon;
		this.href = href;
		this.spread = spread;
		this.children = children;
		this.level = level;
		this.status = status;
		this.parent = parent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 60)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "icon", length = 60)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "href", length = 60)
	public String getHref() {
		return this.href;
	}

	public void setHref(String href) {
		this.href = href;
	}

	@Column(name = "spread")
	public Integer getSpread() {
		return this.spread;
	}

	public void setSpread(Integer spread) {
		this.spread = spread;
	}

	@Column(name = "children", length = 65535)
	public String getChildren() {
		return this.children;
	}

	public void setChildren(String children) {
		this.children = children;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "parent", length = 60)
	public String getParent() {
		return this.parent;
	}

	public void setParent(String parent) {
		this.parent = parent;
	}

}
