package com.changuang.domain.entity;
// Generated 2017-10-30 17:04:44 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PageManage generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "page_manage", catalog = "tochatting")
public class PageManage implements java.io.Serializable {

	private Integer recid;
	private Integer usertyperecid;
	private Integer pageid;

	public PageManage() {
	}

	public PageManage(Integer usertyperecid, Integer pageid) {
		this.usertyperecid = usertyperecid;
		this.pageid = pageid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "usertyperecid")
	public Integer getUsertyperecid() {
		return this.usertyperecid;
	}

	public void setUsertyperecid(Integer usertyperecid) {
		this.usertyperecid = usertyperecid;
	}

	@Column(name = "pageid")
	public Integer getPageid() {
		return this.pageid;
	}

	public void setPageid(Integer pageid) {
		this.pageid = pageid;
	}

}
