package com.changuang.domain.entity;
// Generated 2017-12-1 14:27:22 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * ReplySheet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "reply_sheet", catalog = "tochatting")
public class ReplySheet implements java.io.Serializable {

	private Integer recid;
	private Integer userRecid;
	private Integer commentRecid;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date createTime;
	private String replyContent;
	private Integer replyUserrecid;

	public ReplySheet() {
	}

	public ReplySheet(Integer userRecid, Integer commentRecid, Date createTime, String replyContent,
			Integer replyUserrecid) {
		this.userRecid = userRecid;
		this.commentRecid = commentRecid;
		this.createTime = createTime;
		this.replyContent = replyContent;
		this.replyUserrecid = replyUserrecid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "user_recid")
	public Integer getUserRecid() {
		return this.userRecid;
	}

	public void setUserRecid(Integer userRecid) {
		this.userRecid = userRecid;
	}

	@Column(name = "comment_recid")
	public Integer getCommentRecid() {
		return this.commentRecid;
	}

	public void setCommentRecid(Integer commentRecid) {
		this.commentRecid = commentRecid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "reply_content")
	public String getReplyContent() {
		return this.replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	@Column(name = "reply_userrecid")
	public Integer getReplyUserrecid() {
		return this.replyUserrecid;
	}

	public void setReplyUserrecid(Integer replyUserrecid) {
		this.replyUserrecid = replyUserrecid;
	}

}
