package com.changuang.domain.entity;
// Generated 2017-12-1 14:27:22 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * ReportSheet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "report_sheet", catalog = "tochatting")
public class ReportSheet implements java.io.Serializable {

	private Integer recid;
	private Integer userRecid;
	private String reportContent;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date createTime;
	private Integer isreading;
	private String reader;
	private String replyContent;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date replyTime;
	private Integer anchorRecid;

	public ReportSheet() {
	}

	public ReportSheet(Integer userRecid, String reportContent, Date createTime, Integer isreading, String reader,
			String replyContent, Date replyTime, Integer anchorRecid) {
		this.userRecid = userRecid;
		this.reportContent = reportContent;
		this.createTime = createTime;
		this.isreading = isreading;
		this.reader = reader;
		this.replyContent = replyContent;
		this.replyTime = replyTime;
		this.anchorRecid = anchorRecid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "user_recid")
	public Integer getUserRecid() {
		return this.userRecid;
	}

	public void setUserRecid(Integer userRecid) {
		this.userRecid = userRecid;
	}

	@Column(name = "report_content")
	public String getReportContent() {
		return this.reportContent;
	}

	public void setReportContent(String reportContent) {
		this.reportContent = reportContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "isreading")
	public Integer getIsreading() {
		return this.isreading;
	}

	public void setIsreading(Integer isreading) {
		this.isreading = isreading;
	}

	@Column(name = "reader", length = 50)
	public String getReader() {
		return this.reader;
	}

	public void setReader(String reader) {
		this.reader = reader;
	}

	@Column(name = "reply_content")
	public String getReplyContent() {
		return this.replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reply_time", length = 19)
	public Date getReplyTime() {
		return this.replyTime;
	}

	public void setReplyTime(Date replyTime) {
		this.replyTime = replyTime;
	}

	@Column(name = "anchor_recid")
	public Integer getAnchorRecid() {
		return this.anchorRecid;
	}

	public void setAnchorRecid(Integer anchorRecid) {
		this.anchorRecid = anchorRecid;
	}

}
