package com.changuang.domain.entity;
// Generated 2017-12-1 14:27:22 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * RewardSheet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "reward_sheet", catalog = "tochatting")
public class RewardSheet implements java.io.Serializable {

	private Integer recid;
	private Integer userRecid;
	private Integer anchorRecid;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date createTime;
	private Float rewardAmount;
	private Integer giftRecid;
	private Integer giftNumber;

	public RewardSheet() {
	}

	public RewardSheet(Integer userRecid, Integer anchorRecid, Date createTime, Float rewardAmount, Integer giftRecid,
			Integer giftNumber) {
		this.userRecid = userRecid;
		this.anchorRecid = anchorRecid;
		this.createTime = createTime;
		this.rewardAmount = rewardAmount;
		this.giftRecid = giftRecid;
		this.giftNumber = giftNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "user_recid")
	public Integer getUserRecid() {
		return this.userRecid;
	}

	public void setUserRecid(Integer userRecid) {
		this.userRecid = userRecid;
	}

	@Column(name = "anchor_recid")
	public Integer getAnchorRecid() {
		return this.anchorRecid;
	}

	public void setAnchorRecid(Integer anchorRecid) {
		this.anchorRecid = anchorRecid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "reward_amount", precision = 12, scale = 0)
	public Float getRewardAmount() {
		return this.rewardAmount;
	}

	public void setRewardAmount(Float rewardAmount) {
		this.rewardAmount = rewardAmount;
	}

	@Column(name = "gift_recid")
	public Integer getGiftRecid() {
		return this.giftRecid;
	}

	public void setGiftRecid(Integer giftRecid) {
		this.giftRecid = giftRecid;
	}

	@Column(name = "gift_number")
	public Integer getGiftNumber() {
		return this.giftNumber;
	}

	public void setGiftNumber(Integer giftNumber) {
		this.giftNumber = giftNumber;
	}

}
