package com.changuang.domain.entity;
// Generated 2017-12-1 14:27:22 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * UserRecharge generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "user_recharge", catalog = "tochatting")
public class UserRecharge implements java.io.Serializable {

	private Integer recid;
	private Integer userRecid;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date createTime;
	private String rechargeRecid;
	private Float rechargeAmount;

	public UserRecharge() {
	}

	public UserRecharge(Integer userRecid, Date createTime, String rechargeRecid, Float rechargeAmount) {
		this.userRecid = userRecid;
		this.createTime = createTime;
		this.rechargeRecid = rechargeRecid;
		this.rechargeAmount = rechargeAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "user_recid")
	public Integer getUserRecid() {
		return this.userRecid;
	}

	public void setUserRecid(Integer userRecid) {
		this.userRecid = userRecid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "recharge_recid", length = 50)
	public String getRechargeRecid() {
		return this.rechargeRecid;
	}

	public void setRechargeRecid(String rechargeRecid) {
		this.rechargeRecid = rechargeRecid;
	}

	@Column(name = "recharge_amount", precision = 12, scale = 0)
	public Float getRechargeAmount() {
		return this.rechargeAmount;
	}

	public void setRechargeAmount(Float rechargeAmount) {
		this.rechargeAmount = rechargeAmount;
	}

}
