package com.changuang.domain.entity;
// Generated 2017-12-1 14:27:22 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * VoiceSheet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "voice_sheet", catalog = "tochatting")
public class VoiceSheet implements java.io.Serializable {

	private Integer recid;
	private Integer anchorRecid;
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	private Date createTime;
	private String voiceLabel;
	private String roomName;
	private Integer isFree;
	private Integer isHot;
	private Integer isRecommend;

	public VoiceSheet() {
	}

	public VoiceSheet(Integer anchorRecid, Date createTime, String voiceLabel, String roomName, Integer isFree,
			Integer isHot, Integer isRecommend) {
		this.anchorRecid = anchorRecid;
		this.createTime = createTime;
		this.voiceLabel = voiceLabel;
		this.roomName = roomName;
		this.isFree = isFree;
		this.isHot = isHot;
		this.isRecommend = isRecommend;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recid", unique = true, nullable = false)
	public Integer getRecid() {
		return this.recid;
	}

	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	@Column(name = "anchor_recid")
	public Integer getAnchorRecid() {
		return this.anchorRecid;
	}

	public void setAnchorRecid(Integer anchorRecid) {
		this.anchorRecid = anchorRecid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "voice_label", length = 20)
	public String getVoiceLabel() {
		return this.voiceLabel;
	}

	public void setVoiceLabel(String voiceLabel) {
		this.voiceLabel = voiceLabel;
	}

	@Column(name = "room_name", length = 20)
	public String getRoomName() {
		return this.roomName;
	}

	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}

	@Column(name = "is_free")
	public Integer getIsFree() {
		return this.isFree;
	}

	public void setIsFree(Integer isFree) {
		this.isFree = isFree;
	}

	@Column(name = "is_hot")
	public Integer getIsHot() {
		return this.isHot;
	}

	public void setIsHot(Integer isHot) {
		this.isHot = isHot;
	}

	@Column(name = "is_recommend")
	public Integer getIsRecommend() {
		return this.isRecommend;
	}

	public void setIsRecommend(Integer isRecommend) {
		this.isRecommend = isRecommend;
	}

}
